# Main configuration file for pytpt examples
# This file sets up the default configuration structure

defaults:
  - database: teradata_nfl
  - _self_

# Data directory configuration
data:
  dir: "../../data"